name: Create Release Test Workflow

on:
  pull_request:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v1
      with:
        auto-update-conda: true
        auto-activate-base: false
        activate-environment: jlabrelease_master
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
    - name: Prepare release
      run: |
        source scripts/release_prep.sh master
    - name: Bump release
      run: |
        jlpm bumpversion release
    # See https://github.com/marketplace/actions/install-ssh-key
    - name: Publish npm packages
      run: echo "not yet!"
      # npm run publish:all
    # - name: Create Release
    #   id: create_release
    #   uses: ncipollo/release-action@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag: ${{ github.event.release.tag_name }}
    #     name: Release ${{ github.event.release.tag_name }}
    #     artifacts: ${{ env.CURRENT_LOCALE_DIR }}/dist/*
    #     body: Release ${{ github.event.release.tag_name }}
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     draft: True
      # twine upload dist/*
    - name: Push tags and commits
      run: echo "Not yet!"
      # git push origin --tags <BRANCH>
